apiVersion: apps/v1
kind: Deployment

metadata:
  name: transaction-service
  namespace: logbook

spec:
  replicas: 1

  selector:
    matchLabels:
      app: transaction-service

  template:
    metadata:
      labels:
        app: transaction-service

    spec:
      containers:
      - name: transaction-service

        image: vaishnavisaw01/transaction-service:v2
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 3004

        env:
        - name: PORT
          value: "3004"

        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: logbook-secrets
              key: MONGO_URI

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: logbook-secrets
              key: JWT_SECRET

        livenessProbe:
          httpGet:
            path: /healthz
            port: 3004
          initialDelaySeconds: 10
          periodSeconds: 15

        readinessProbe:
          httpGet:
            path: /healthz
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 10

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"

          limits:
            memory: "512Mi"
            cpu: "500m"
