apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service
  namespace: logbook

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
      - name: auth-service

        image: vaishnavisaw01/auth-service:v2
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 3001

        env:
        - name: PORT
          value: "3001"

        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: logbook-secrets
              key: MONGO_URI

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: logbook-secrets
              key: JWT_SECRET

        livenessProbe:
          httpGet:
            path: /healthz
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 15

        readinessProbe:
          httpGet:
            path: /healthz
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"

          limits:
            memory: "512Mi"
            cpu: "500m"
